# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcaf14e0d4e6d29b8bd708665a9725b237fc0eff3f78dd58036a64c7e7543e7842c3db0bb168f04904274f87df81749c75fc9beb9a284bb44003c56fb4a5088e

test:
  secret_key_base: fbd980ff38210d5b7d0f235aced67b7d40cc2d8b0cf7d78427c982e69f76ad0102d11d90a7b937d9221afd9a80144a3e104e299e0cf871ae59a02e91ce3a7b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
